import * as React from 'react';
import axios from 'axios';
import * as ReactDOM from 'react-dom';
import { Game } from '~/ui/game';
import { Lobby } from '~/ui/lobby';
import { Start } from '~/ui/start';

export const App = () => {
  // { user } when logged in, { pending } while waiting for email
  // verification, {} when logged out; null until the server answers.
  const [account, setAccount] = React.useState(null);

  React.useEffect(() => {
    axios
      .get('/api/me')
      .then(({ data }) => setAccount(data))
      .catch(() => setAccount({}));
  }, []);

  const path = window.location.pathname;
  let gameID = window.selectedGameID || null;
  if (!gameID && document.location.hash) gameID = document.location.hash.slice(1);

  let pane;
  if (account === null) {
    pane = <p className="loading">Loading&hellip;</p>;
  } else if (!account.user) {
    // Logon is required for everything; a board link lands here first.
    pane = <Start account={account} setAccount={setAccount} openLogin={!!gameID} />;
  } else if (gameID) {
    pane = <Game gameID={gameID} />;
  } else if (path === '/quick') {
    pane = <Lobby defaultGameID={window.autogeneratedGameID} />;
  } else {
    pane = <Start account={account} setAccount={setAccount} openLogin={false} />;
  }

  return (
    <div id="application">
      <div id="topbar">
        <h1>
          <a href="/">ClueMeIn</a>
        </h1>
      </div>
      {pane}
    </div>
  );
};

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(<App />, document.getElementById('app'));
});
