// ClueMeIn server (Node port of HorsePaste's Go server).
// Boards still live in memory; RuleSets and sessions will move them to the database.
require('dotenv').config({ quiet: true, path: require('path').join(__dirname, '.env') });
const fs = require('fs');
const path = require('path');
const express = require('express');
const { Game, randomState, nextGameState } = require('./game');
const { initDb, normalizeWord } = require('./db');
const { setupAuth } = require('./auth');
const { setupRulesets } = require('./rulesets');

const PORT = process.env.PORT || 3003;
const LONG_POLL_MS = 15 * 1000;

const db = initDb();

const listWordsStmt = db.prepare(
  'SELECT word FROM standard_words WHERE wordlist_id = ? ORDER BY word'
);

function wordsForLists(ids) {
  const words = new Set();
  for (const id of ids) {
    for (const { word } of listWordsStmt.all(id)) words.add(word);
  }
  return [...words];
}

const originalList = db.prepare("SELECT id FROM wordlists WHERE name = 'Original'").get();
const defaultWords = wordsForLists([originalList.id]).sort();

const gameIDWords = fs
  .readFileSync(path.join(__dirname, 'assets', 'game-id-words.txt'), 'utf8')
  .split(/\r?\n/)
  .map((w) => w.trim().toLowerCase())
  .filter((w) => w.length >= 3);

// id -> { game, waiters: Set<fn> }. Waiters are pending long-poll requests.
const games = new Map();

function notify(handle) {
  const waiters = [...handle.waiters];
  handle.waiters.clear();
  waiters.forEach((fn) => fn());
}

function getHandle(id) {
  let handle = games.get(id);
  if (!handle) {
    handle = { game: new Game(id, randomState(defaultWords)), waiters: new Set() };
    games.set(id, handle);
  }
  return handle;
}

function autogeneratedID() {
  for (let i = 0; ; i++) {
    const count = 2 + Math.floor(i / 5);
    const words = [];
    for (let j = 0; j < count; j++) {
      words.push(gameIDWords[Math.floor(Math.random() * gameIDWords.length)]);
    }
    const id = words.join('-');
    if (!games.has(id)) return id;
  }
}

// Escape a value for embedding in an inline <script>.
function jsString(s) {
  return JSON.stringify(s).replace(/</g, '\\u003c');
}

function renderIndex(selectedGameID) {
  return `<!DOCTYPE html>
<html>
  <head>
    <title>ClueMeIn</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="/static/app.js" type="text/javascript"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/game.css" />
    <link rel="stylesheet" type="text/css" href="/static/lobby.css" />
    <link rel="stylesheet" type="text/css" href="/static/start.css" />
    <link rel="shortcut icon" type="image/png" id="favicon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAA8SURBVHgB7dHBDQAgCAPA1oVkBWdzPR84kW4AD0LCg36bXJqUcLL2eVY/EEwDFQBeEfPnqUpkLmigAvABK38Grs5TfaMAAAAASUVORK5CYII="/>
    <script type="text/javascript">
      ${selectedGameID ? `window.selectedGameID = ${jsString(selectedGameID)};` : ''}
      window.autogeneratedGameID = ${jsString(autogeneratedID())};
    </script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>`;
}

const app = express();
app.use(express.json({ limit: '2mb' }));
app.use('/static', express.static(path.join(__dirname, 'frontend', 'dist')));
app.set('trust proxy', 1); // Railway terminates HTTPS in front of the app

const { requireAuth } = setupAuth(app, db);
setupRulesets(app, db, requireAuth);

// Everything below except the page itself requires a logged-in player.
app.use(['/game-state', '/guess', '/end-turn', '/next-game', '/api/wordlists'], requireAuth);

// Long-poll: answer immediately if the client's state is stale, otherwise
// wait until the game changes or 15 seconds pass.
app.post('/game-state', (req, res) => {
  const { game_id: gameID, state_id: stateID } = req.body || {};
  if (typeof gameID !== 'string' || !gameID) return res.status(400).send('Missing game_id');

  const handle = getHandle(gameID);
  if (!stateID || handle.game.stateId !== stateID) return res.json(handle.game);

  let done = false;
  const finish = () => {
    if (done) return;
    done = true;
    clearTimeout(timer);
    handle.waiters.delete(finish);
    res.json(getHandle(gameID).game);
  };
  const timer = setTimeout(finish, LONG_POLL_MS);
  handle.waiters.add(finish);
  res.on('close', () => {
    if (done) return;
    done = true;
    clearTimeout(timer);
    handle.waiters.delete(finish);
  });
});

app.post('/guess', (req, res) => {
  const { game_id: gameID, index } = req.body || {};
  const handle = getHandle(gameID);
  try {
    handle.game.guess(index);
  } catch (err) {
    return res.status(400).send(err.message);
  }
  notify(handle);
  res.json(handle.game);
});

app.post('/end-turn', (req, res) => {
  const { game_id: gameID, current_round: currentRound } = req.body || {};
  const handle = getHandle(gameID);
  if (handle.game.nextTurn(currentRound)) notify(handle);
  res.json(handle.game);
});

// Standard word lists, in picker order, with word counts.
app.get('/api/wordlists', (req, res) => {
  res.json(
    db
      .prepare(
        `SELECT l.id, l.name, l.language, l.picker_row, COUNT(w.id) AS count
           FROM wordlists l LEFT JOIN standard_words w ON w.wordlist_id = l.id
          GROUP BY l.id ORDER BY l.picker_row, l.sort_order`
      )
      .all()
  );
});

app.post('/next-game', (req, res) => {
  const body = req.body || {};
  const gameID = body.game_id;
  if (typeof gameID !== 'string' || !gameID) return res.status(400).send('Missing game_id');

  // Words come from standard lists (by id) plus any explicit words, e.g. a
  // custom list or the previous board's word set.
  const listIDs = (body.wordlist_ids || []).map(Number).filter(Number.isInteger);
  const wordSet = [
    ...new Set([
      ...wordsForLists(listIDs),
      ...(body.word_set || []).map(normalizeWord).filter(Boolean),
    ]),
  ].sort();
  if (wordSet.length > 0 && wordSet.length < 25) return res.status(400).send('Need at least 25 words');
  if (wordSet.length > 10000) return res.status(400).send('Too many words in the set.');

  const words = wordSet.length ? wordSet : defaultWords;
  const opts = {
    timer_duration_ms: Number(body.timer_duration_ms) || 0,
    enforce_timer: !!body.enforce_timer,
  };

  let handle = games.get(gameID);
  if (!handle) {
    handle = { game: new Game(gameID, randomState(words), opts), waiters: new Set() };
    games.set(gameID, handle);
  } else if (body.create_new) {
    handle.game = new Game(gameID, nextGameState(handle.game.state), opts);
    notify(handle);
  }
  res.json(handle.game);
});

// The single page; the front end picks the screen from the path
// ("/", "/create", "/modify/:id", "/quick", "/game/:id").
app.get('/game/:id', (req, res) => res.type('html').send(renderIndex(req.params.id)));
app.get('*', (req, res) => {
  if (req.path.startsWith('/api/')) return res.status(404).json({ error: 'Not found' });
  res.type('html').send(renderIndex(''));
});

// Drop finished games after 3 hours and any game after 72 hours.
setInterval(() => {
  const now = Date.now();
  for (const [id, handle] of games) {
    const age = now - Date.parse(handle.game.created_at);
    if ((handle.game.winning_team && age > 3 * 3600e3) || age > 72 * 3600e3) {
      games.delete(id);
    }
  }
}, 10 * 60 * 1000).unref();

app.listen(PORT, () => console.log(`ClueMeIn listening on http://localhost:${PORT}`));
