// ClueMeIn server (Node port of HorsePaste's Go server).
// Phase 1: games live in memory only; persistence arrives with the database.
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const express = require('express');
const { Game, randomState, nextGameState } = require('./game');

const PORT = process.env.PORT || 3000;
const LONG_POLL_MS = 15 * 1000;

function loadWordFile(file) {
  return fs
    .readFileSync(path.join(__dirname, 'assets', file), 'utf8')
    .split(/\r?\n/)
    .map((w) => w.trim())
    .filter(Boolean);
}

const defaultWords = loadWordFile('original.txt').sort();
const gameIDWords = loadWordFile('game-id-words.txt')
  .filter((w) => w.length >= 3)
  .map((w) => w.toLowerCase());

// id -> { game, waiters: Set<fn> }. Waiters are pending long-poll requests.
const games = new Map();

function notify(handle) {
  const waiters = [...handle.waiters];
  handle.waiters.clear();
  waiters.forEach((fn) => fn());
}

function getHandle(id) {
  let handle = games.get(id);
  if (!handle) {
    handle = { game: new Game(id, randomState(defaultWords)), waiters: new Set() };
    games.set(id, handle);
  }
  return handle;
}

function autogeneratedID() {
  for (let i = 0; ; i++) {
    const count = 2 + Math.floor(i / 5);
    const words = [];
    for (let j = 0; j < count; j++) {
      words.push(gameIDWords[Math.floor(Math.random() * gameIDWords.length)]);
    }
    const id = words.join('-');
    if (!games.has(id)) return id;
  }
}

// Escape a value for embedding in an inline <script>.
function jsString(s) {
  return JSON.stringify(s).replace(/</g, '\\u003c');
}

function renderIndex(selectedGameID) {
  return `<!DOCTYPE html>
<html>
  <head>
    <title>ClueMeIn</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="/static/app.js" type="text/javascript"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/game.css" />
    <link rel="stylesheet" type="text/css" href="/static/lobby.css" />
    <link rel="shortcut icon" type="image/png" id="favicon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAA8SURBVHgB7dHBDQAgCAPA1oVkBWdzPR84kW4AD0LCg36bXJqUcLL2eVY/EEwDFQBeEfPnqUpkLmigAvABK38Grs5TfaMAAAAASUVORK5CYII="/>
    <script type="text/javascript">
      ${selectedGameID ? `window.selectedGameID = ${jsString(selectedGameID)};` : ''}
      window.autogeneratedGameID = ${jsString(autogeneratedID())};
    </script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>`;
}

const app = express();
app.use(express.json({ limit: '2mb' }));
app.use('/static', express.static(path.join(__dirname, 'frontend', 'dist')));

// Long-poll: answer immediately if the client's state is stale, otherwise
// wait until the game changes or 15 seconds pass.
app.post('/game-state', (req, res) => {
  const { game_id: gameID, state_id: stateID } = req.body || {};
  if (typeof gameID !== 'string' || !gameID) return res.status(400).send('Missing game_id');

  const handle = getHandle(gameID);
  if (!stateID || handle.game.stateId !== stateID) return res.json(handle.game);

  let done = false;
  const finish = () => {
    if (done) return;
    done = true;
    clearTimeout(timer);
    handle.waiters.delete(finish);
    res.json(getHandle(gameID).game);
  };
  const timer = setTimeout(finish, LONG_POLL_MS);
  handle.waiters.add(finish);
  res.on('close', () => {
    if (done) return;
    done = true;
    clearTimeout(timer);
    handle.waiters.delete(finish);
  });
});

app.post('/guess', (req, res) => {
  const { game_id: gameID, index } = req.body || {};
  const handle = getHandle(gameID);
  try {
    handle.game.guess(index);
  } catch (err) {
    return res.status(400).send(err.message);
  }
  notify(handle);
  res.json(handle.game);
});

app.post('/end-turn', (req, res) => {
  const { game_id: gameID, current_round: currentRound } = req.body || {};
  const handle = getHandle(gameID);
  if (handle.game.nextTurn(currentRound)) notify(handle);
  res.json(handle.game);
});

app.post('/next-game', (req, res) => {
  const body = req.body || {};
  const gameID = body.game_id;
  if (typeof gameID !== 'string' || !gameID) return res.status(400).send('Missing game_id');

  const wordSet = [
    ...new Set((body.word_set || []).map((w) => String(w).trim().toUpperCase()).filter(Boolean)),
  ].sort();
  if (wordSet.length > 0 && wordSet.length < 25) return res.status(400).send('Need at least 25 words');
  if (wordSet.length > 10000) return res.status(400).send('Too many words in the set.');

  const words = wordSet.length ? wordSet : defaultWords;
  const opts = {
    timer_duration_ms: Number(body.timer_duration_ms) || 0,
    enforce_timer: !!body.enforce_timer,
  };

  let handle = games.get(gameID);
  if (!handle) {
    handle = { game: new Game(gameID, randomState(words), opts), waiters: new Set() };
    games.set(gameID, handle);
  } else if (body.create_new) {
    handle.game = new Game(gameID, nextGameState(handle.game.state), opts);
    notify(handle);
  }
  res.json(handle.game);
});

app.get('/:id?', (req, res) => {
  res.type('html').send(renderIndex(req.params.id || ''));
});

// Drop finished games after 3 hours and any game after 72 hours.
setInterval(() => {
  const now = Date.now();
  for (const [id, handle] of games) {
    const age = now - Date.parse(handle.game.created_at);
    if ((handle.game.winning_team && age > 3 * 3600e3) || age > 72 * 3600e3) {
      games.delete(id);
    }
  }
}, 10 * 60 * 1000).unref();

app.listen(PORT, () => console.log(`ClueMeIn listening on http://localhost:${PORT}`));
